theme = "main"
client_id = "fb9c6f0fd604439e8a6ac868290354c3"
client_port = 8080
playback_format = """{track} • {album} • {artists}\n\n\n\n{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = ""
pause_icon = "󰏥"
liked_icon = "󰣐"
border_type = "Rounded"
progress_bar_type = "Line"
enable_media_control = true
enable_streaming = "Never"
enable_cover_image_cache = true
default_device = "arch101-0"
cover_img_scale = 2.2

[copy_command]
command = "wl-copy"
args = []

[layout]
library = { album_percent = 40, playlist_percent = 40 }
playback_window_height = 6
playback_window_position = "Top"
