[[themes]]
name = "main"
[themes.palette]
black = "#000000"
red = "#ff1616"
green = "#7cd605"
yellow = "#feb301"
blue = "#3073d9"
magenta = "#d135de"
cyan = "#13dd7e"
white = "#fef2d0"
[themes.component_style]
selection = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_track = { fg = "White", modifiers = ["Bold"] }
playback_album = { fg = "White", modifiers = ["Bold"] }
playback_artists = { fg = "White", modifiers = ["Bold"] }
playback_progress_bar = { fg = "Green" }
playback_progress_bar_unfilled = { fg = "Red" }
