[[manager.append_keymap]]
on = [ "b" ]
run = "cd ~"

[[manager.prepend_keymap]]
on = [ "<C-q>"]
run = "quit --no-cwd-file"

[[manager.prepend_keymap]]
on = [ "I" ]
run = "shell --confirm --orphan swayimg $1"
