[[manager.append_keymap]]
on = [ "b" ]
run = "cd ~"

[[manager.prepend_keymap]]
on = [ "<C-q>"]
run = "quit --no-cwd-file"

[[manager.prepend_keymap]]
on = [ "i" ]
run = 'shell --confirm --orphan "swayimg \"$@\""'

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "R"
run = 'shell --confirm --block "gtrash restore"'

[[manager.prepend_keymap]]
on = "n"
run = 'shell --confirm --block "$EDITOR"'
