[manager]
hovered = { fg = "magenta" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "yellow" },

	# Media
	{ mime = "{audio,video}/*", fg = "white" },

	# Archives
	{ mime = "application/{,g}zip", fg = "red" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "red" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "cyan" },

	# Empty files
	# { mime = "inode/x-empty", fg = "red" },

	# Special files
	{ name = "*", is = "orphan", fg = "red" },
	{ name = "*", is = "exec"  , fg = "green" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]

