#!/bin/sh

if [ -n "$(bluetoothctl devices Connected)" ]; then
    echo 1
elif [ -n "$(pactl list sinks | grep bluez)" ]; then
    # This stupid hack only needs to be here because - for whatever reason -
    # "bluetoothctl devices Connected" doesn't show devices that auto-connected
    # because their are trusted!!! - very mad
    echo 1
else
    echo 0
fi