#!/bin/sh

if [ "$1" = "-c" -o "$1" = "--caps-lock" ]; then
	builtin_caps=$(cat /sys/class/leds/input5::capslock/brightness)
	if [ "$builtin_caps" = 1 ]; then
		echo "$builtin_caps"
    else 
        cat /sys/class/leds/input14::capslock/brightness
    fi
elif [ "$1" = "-n" -o "$1" = "--num-lock" ]; then
	builtin_nums=$(cat /sys/class/leds/input5::numlock/brightness)
	if [ "$builtin_nums" = 1 ]; then
		echo "$builtin_nums"
    else 
        cat /sys/class/leds/input14::numlock/brightness
    fi
else 
    echo "Wrong usage:"
    echo "-c --caps-lock prints capslock state"
    echo "-n --nums-lock prints numlock state"
fi

if [ "$2" = "-c" -o "$2" = "--caps-lock" ]; then
	builtin_caps=$(cat /sys/class/leds/input5::capslock/brightness)
	if [ "$builtin_caps" = 1 ]; then
		echo "$builtin_caps"
    else 
        cat /sys/class/leds/input14::capslock/brightness
    fi
elif [ "$2" = "-n" -o "$2" = "--num-lock" ]; then
	builtin_nums=$(cat /sys/class/leds/input5::numlock/brightness)
	if [ "$builtin_nums" = 1 ]; then
		echo "$builtin_nums"
    else 
        cat /sys/class/leds/input14::numlock/brightness
    fi
elif [ -z "$2" ]; then 
    exit
else 
    echo "Wrong usage:"
    echo "-c --caps-lock prints capslock state"
    echo "-n --nums-lock prints numlock state"
fi

